config/routes.rb
Rails.application.routes.draw do
  post '/products', to: 'products#create'
  get '/products/new', to: 'products#new', as: :new_product
  get '/products', to: 'products#index'
  get '/products/:id', to: 'products#show', as: :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  # Esto es para que sea obligatorio llenar todos los campos del formulario
  # y que el usuario no se olvide de completar ningun campo.
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # Devuelve todos los productos.
    def index
        @products = Product.all
    end

    # Devuelve un solo producto y lo encuentra por su id.
    def show
        @product = Product.find(params[:id])
    end

    # Crea un nuevo producto
    def new
        @product = Product.new
    end

    # Le pasamos los parametros a un producto nuevo para que se rellene el formulario a agregar.
    def create
        @product = Product.new(product_params)

        # Si al crear un nuevo producto se guarda satisfactoriamente
        # en la base de datos que nos redirija a home.
        if @product.save
            redirect_to products_path

        # En cambio si no se guarda vamos a renderizar
        # el formulario "new" de nuevo.
        else
         render :new
        end
    end

    private
    # Recoge todos los parametros, y vamos a necesitar que tenga un objeto ":product"
    # y que solo permita los parametros que queremos nosotros(title, description, price)
    def product_params
        params.require(:product).permit(:title, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- render 'shared/header' es un partial html que se encuentra en esta direccion 'shared/header'-->
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Productos:</h1>

<!-- @products llama a la variable declarada en el controlador products-->
<% @products.each do |product| %>
    <%= link_to product_path(product), class: 'product' do %>
    <!-- @products.title llama a la variable declarada en el controlador products
    y nos devuelve la columna title de nuestra tabla products -->
    <h2><%= product.title %></h2>
    <h1><%= product.price %></h1>
    <% end %>
<% end %>

app/views/products/new.html.erb
<h2>Añadir Producto</h2>

<%= form_with model: @product do |form| %>
     <div>
        <%= form.label :title %>
         <%= form.text_field :title %>
     </div>

     <div>
         <%= form.label :description %>
         <%= form.text_area :description %>
     </div>

     <div>
         <%= form.label :price %>
         <%= form.number_field :price %>
     </div>

     <%= form.submit %>
<% end %>

app/views/products/show.html.erb
<h1 class="title"><%= @product.title %></h1>

<p class="description"><%= @product.description %></p>

<span class="price"><%= @product.price %>$</span>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
<h1>vendelo</h1>
<% end %>

<%= link_to 'Añadir producto', new_product_path %>